services:
  db:
    image: postgres:16
    container_name: ${COMPOSE_PROJECT_NAME:-myapp}-db
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-foerderantrag}
      POSTGRES_DB: ${POSTGRES_DB:-foerderantrag_db}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-foerderantrag_db}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data:
